### PR TITLE
Add dojoType to button

### PR DESCRIPTION
**Pull request by sboulema**
Add dojoType attribute to button to improve styling

### CODE REVIEW

**Comment by sboulema** [comment]
Normal state:
image

Hover state:
image

**Comment by nneul** [comment]
I like the intent - however, it makes it WAY too subtle if next to the existing:

image

Wondering if there is some other styling that could additionally be applied to call out the difference. The 'ugly' default button is very clear/distinct in appearance from the Mark as read dropdown menu.

**Comment by sboulema** [comment]
True... good point, first thing I did after installing your plugin was hiding the old button...

Another option would be going icon-only with a title tag:
image

**Comment by nneul** [comment]
Hmm... I saw your readme update - wonder if I should just stuff that in optionally with the plugin as an inline style. 

Let me try something with that tonight and I'll get back to you. I do like the double checkmark though! That combined with the Mark as read would completely work for me.  If you want to adjust PR to that, I will definitely merge it.

**Pull request merged**
